/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// PORTA MACROS
#define GPIOA_BASE 		0X40010800
#define GPIOA_CHR		*(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR		*(vuint32_t *)(GPIOA_BASE + 0x0C)

#define RCC_BASE		0x40021000
#define RCC_APB2ENR		*(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR		*(vuint32_t *)(RCC_BASE + 0x04)


int main(void)
{

	// set clock of APB2 to 2MHz

	/*
	PPRE2: APB high-speed prescaler (APB2)
		Set and cleared by software to control the division factor of the APB high-speed clock
		(PCLK2).
		0xx: HCLK not divided
		100: HCLK divided by 2
		101: HCLK divided by 4
		110: HCLK divided by 8
		111: HCLK divided by 16
	 */

	RCC_CFGR  	&= ~(7<<11);
	RCC_CFGR  	|= 5<<11;

	// set clock of APB1 to 4MHz

	/*
	Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
		Set and cleared by software to control the division factor of the APB low-speed clock
		(PCLK1).
		Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain.
		0xx: HCLK not divided
		100: HCLK divided by 2
		101: HCLK divided by 4
		110: HCLK divided by 8
		111: HCLK divided by 16
	*/

	RCC_CFGR  	&= ~(7<<8);
	RCC_CFGR  	|= 4<<8;

	// set clock of AHB to 4MHz

	/*
	4 HPRE: AHB prescaler
		Set and cleared by software to control the division factor of the AHB clock.
		0xxx: SYSCLK not divided
		1000: SYSCLK divided by 2
		1001: SYSCLK divided by 4
		1010: SYSCLK divided by 8
		1011: SYSCLK divided by 16
		1100: SYSCLK divided by 64
		1101: SYSCLK divided by 128
		1110: SYSCLK divided by 256
		1111: SYSCLK divided by 512
	*/

	RCC_CFGR  	&= ~(7<<5);

	// set clock of SYSCLK to be get from internal HSI_RC

	/*
	SW: System clock switch
		Set and cleared by software to select SYSCLK source.
		Set by hardware to force HSI selection when leaving Stop and Standby mode or in case of
		failure of the HSE oscillator used directly or indirectly as system clock (if the Clock Security
		System is enabled).
		00: HSI selected as system clock
		01: HSE selected as system clock
		10: PLL selected as system clock
		11: not allowed
	*/

	RCC_CFGR	&= ~(3);

	// ================ enable clock on portA ================

	/*
	Bit 2 IOPAEN: I/O port A clock enable
		Set and cleared by software.
		0: I/O port A clock disabled
		1:I/O port A clock enabled
	*/

	RCC_APB2ENR |= 1<<2;

	// ================ Initialize PortAS ================

	GPIOA_CHR &= 0xFF0FFFFF;
	GPIOA_CHR |= 0x00200000;

	// ================ Main Function ================

	int i;
	while(1){
		GPIOA_ODR |= 1<<13;
		for (i = 0; i < 5000; ++i);
		GPIOA_ODR &= ~(1<<13);
		for (i = 0; i < 5000; ++i);
	}
}
