/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// PORTA MACROS
#define GPIOA_BASE 		0X40010800
#define GPIOA_CHR		*(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR		*(vuint32_t *)(GPIOA_BASE + 0x0C)

#define RCC_BASE		0x40021000
#define RCC_APB2ENR		*(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR		*(vuint32_t *)(RCC_BASE + 0x04)
#define RCC_CR			*(vuint32_t *)(RCC_BASE + 0x00)


int main(void)
{
	// ================ select PLLSRC HSI_RC / 2 ================

	/*
 	Bit 16 PLLSRC: PLL entry clock source
		Set and cleared by software to select PLL clock source. This bit can be written only when
		PLL is disabled.
		0: HSI oscillator clock / 2 selected as PLL input clock
		1: HSE oscillator clock selected as PLL input clock
	*/

	RCC_CFGR	&= ~(1<<16);

	// ================ modify PLLMUL (multiply (HSI_RC /2) * 8 = 32MHz) ================

	/*
	Bits 21:18 PLLMUL: PLL multiplication factor
		These bits are written by software to define the PLL multiplication factor. These bits can be
		written only when PLL is disabled.
		Caution: The PLL output frequency must not exceed 72 MHz.
		0000: PLL input clock x 2
		0001: PLL input clock x 3
		0010: PLL input clock x 4
		0011: PLL input clock x 5
		0100: PLL input clock x 6
		0101: PLL input clock x 7
		0110: PLL input clock x 8
		0111: PLL input clock x 9
		1000: PLL input clock x 10
		1001: PLL input clock x 11
		1010: PLL input clock x 12
		1011: PLL input clock x 13
		1100: PLL input clock x 14
		1101: PLL input clock x 15
		1110: PLL input clock x 16
		1111: PLL input clock x 16
	*/

	RCC_CFGR	&= ~(0b1111<<18);
	RCC_CFGR	|= (0b0110<<18);

	//  ================ set SW ( clock of SYSCLK to be get from PLL (32MHz) ) ================

	/*
	SW: System clock switch
		Set and cleared by software to select SYSCLK source.
		Set by hardware to force HSI selection when leaving Stop and Standby mode or in case of
		failure of the HSE oscillator used directly or indirectly as system clock (if the Clock Security
		System is enabled).
		00: HSI selected as system clock
		01: HSE selected as system clock
		10: PLL selected as system clock
		11: not allowed
	*/

	RCC_CFGR	&= ~(3);
	RCC_CFGR	|= 0b10;

	// ================ set clock of AHB to 4MHz ================

	/*
	4 HPRE: AHB prescaler
		Set and cleared by software to control the division factor of the AHB clock.
		0xxx: SYSCLK not divided
		1000: SYSCLK divided by 2
		1001: SYSCLK divided by 4
		1010: SYSCLK divided by 8
		1011: SYSCLK divided by 16
		1100: SYSCLK divided by 64
		1101: SYSCLK divided by 128
		1110: SYSCLK divided by 256
		1111: SYSCLK divided by 512
	*/
	RCC_CFGR  	&= ~(0b111<<5);

	// ================ set clock of APB2 to 8MHz ================

	/*
	PPRE2: APB high-speed prescaler (APB2)
		Set and cleared by software to control the division factor of the APB high-speed clock
		(PCLK2).
		0xx: HCLK not divided
		100: HCLK divided by 2
		101: HCLK divided by 4
		110: HCLK divided by 8
		111: HCLK divided by 16
	 */
	RCC_CFGR  	&= ~(0b111<<11);
	RCC_CFGR  	|= 0b101<<11;

	// ================ set clock of APB1 to 16MHz ================

	/*
	Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
		Set and cleared by software to control the division factor of the APB low-speed clock
		(PCLK1).
		Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain.
		0xx: HCLK not divided
		100: HCLK divided by 2
		101: HCLK divided by 4
		110: HCLK divided by 8
		111: HCLK divided by 16
	*/

	RCC_CFGR  	&= ~(0b111<<8);
	RCC_CFGR  	|= 0b100<<8;

	// ================ enable PLL ================

	/*
	Bit 28 PLL3ON: PLL3 enable
		Set and cleared by software to enable PLL3.
		Cleared by hardware when entering Stop or Standby mode.
		0: PLL3 OFF
		1: PLL3 ON
	*/

	RCC_CR		|= 1<<24;

	// ================ enable clock on portA ================

	/*
	Bit 2 IOPAEN: I/O port A clock enable
		Set and cleared by software.
		0: I/O port A clock disabled
		1:I/O port A clock enabled
	*/

	RCC_APB2ENR |= 1<<2;

	// ================ Initialize PortAS ================

	GPIOA_CHR &= 0xFF0FFFFF;
	GPIOA_CHR |= 0x00200000;

	// ================ Main Function ================

	int i;
	while(1){
		GPIOA_ODR |= 1<<13;
		for (i = 0; i < 5000; ++i);
		GPIOA_ODR &= ~(1<<13);
		for (i = 0; i < 5000; ++i);
	}
}

