/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

// ================ MACROS ================

// PORTA MACROS
#define GPIOA_BASE 		0X40010800
#define GPIOA_CHR		*(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR		*(vuint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL		*(vuint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_LCKR		*(vuint32_t *)(GPIOA_BASE + 0x18)

// Clock MACROS
#define RCC_BASE		0x40021000
#define RCC_APB2ENR		*(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR		*(vuint32_t *)(RCC_BASE + 0x04)
#define RCC_CR			*(vuint32_t *)(RCC_BASE + 0x00)

// INTERRUPT MACROS
#define EXTI_BASE		0x40010400
#define EXTI_IMR		*(vuint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR		*(vuint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR			*(vuint32_t *)(EXTI_BASE + 0x14)
#define EXTI_SWIER		*(vuint32_t *)(EXTI_BASE + 0x10)

// Alternative Function of GPIO - MACROS
#define AFIO_BASE		0x40010000
#define AFIO_EXTICR1	*(vuint32_t *)(AFIO_BASE + 0x08)

// NVIC
#define NVIC_BASE		0xE000E100
#define NVIC_ISER0	*(vuint32_t *)(NVIC_BASE + 0x00)

// ================ Initialize Interrupt on PA0 ================

void EXTI0_init(void){

	// enable rising trigger
	EXTI_RTSR |= (1<<0);

	// enable exit line 0
	EXTI_IMR |= (1<<0);

	// disable software interrupt
	EXTI_SWIER &= ~(1<<0);

	// NVIC Enabling PA0 interrupt
	NVIC_ISER0 |= 1<<6;

	//EXTI0 configuration to PORTA0
	AFIO_EXTICR1 = 0;
}

// ================ enable clock on portA ================

void PA_clock_init(){
	RCC_APB2ENR |= 1<<2;
}

// ================ Initialize PortAS ================

void GPIOA_PA13_init(){
	// Output Pin 13
	GPIOA_CHR &= 0xFF0FFFFF;
	GPIOA_CHR |= 0x00200000;
}

void GPIOA_PA0_init(){
	// Input pin 0
	GPIOA_CRL &= ~(3<<2);
	GPIOA_CRL |= (0b01<<2);
}

// ================ PA0 Interrupt Service Routine================

void EXTI0_IRQHandler(void){
	// GPIO PA13 toggling
	GPIOA_ODR ^= (1<<13);
	// clear pending interrupt
	EXTI_PR |= 1<<0;
}

int main(void)
{
	GPIOA_LCKR &= ~(1<<16);
	GPIOA_PA0_init();
	GPIOA_PA13_init();
	PA_clock_init();

	EXTI0_init();

    /* Loop forever */
	for(;;);
}
